### PR TITLE
:art:[TAWS-74] update on css color component

### PR DESCRIPTION
**Pull request by ojolanre**
Updates on the CSS color component

### CODE REVIEW

**Review by lax0248917 — DISMISSED** [review]
This all looks great @ojolanre. Nice work!

**Comment by ojolanre** [comment]
> This all looks great @ojolanre. Nice work! 

Thanks Zach

**Comment by mariushilleke** [comment]
Yep, well done, as already said in Slack. Since this will result in a merge conflict, I d suggest the session either on sunday or earlier with e.g. @xeho91 or @lax0248917 before the merge, maybe we can even make a group session out of it to experience the merge conflict together.

**Comment by ojolanre** [comment]
> Yep, well done, as already said in Slack. Since this will result in a merge conflict, I d suggest the session either on sunday or earlier with e.g. @xeho91 or @lax0248917 before the merge, maybe we can even make a group session out of it to experience the merge conflict together.

That would be nice, I'll be able to ask questions about things i don't understand as much, thanks again Marius

**Comment by xeho91** [comment]
@lax0248917 since my internet is terrible, perhaps you would be more capable to present quickly how to deal with merge conflict(s) during Zoom meeting(s) on Monday/Tuesday via livestreaming on Discord?

**Comment by lax0248917** [comment]
I will be hosting a code stream on Sunday starting at 1:00pm EDT. Most likely going till 3-4pm. That would be a great time for us to bring this topic up and I can demonstrate how I would handle this merge conflict.

**Comment by lax0248917** [comment]
One thing to mindful of is that even if we resolve the merge conflict, we still need either @mariushilleke or @xeho91 to approve the request for us to merge.

**Review by xeho91 — APPROVED** [review]

**Comment by mariushilleke** [comment]
Ok, let's try tomorrow at 1230 next to review. I will try to either schedule with google meets or discord, @xeho91 @ojolanre .

**Comment by lax0248917** [comment]
Just reaching out to see if we have covered the process to resolve merge conflicts yet? I apologize for my absence, but am anxious to start back up. Lets please schedule a time to do this. Another option is to video the process and share it with the whole group. Thoughts @TeamArmadilloOrg/lead-dev-team

**Comment by mariushilleke** [comment]
> Just reaching out to see if we have covered the process to resolve merge conflicts yet? I apologize for my absence, but am anxious to start back up. Lets please schedule a time to do this. Another option is to video the process and share it with the whole group. Thoughts @TeamArmadilloOrg/lead-dev-team 

No, not yet. A doodle poll is created in slack

https://doodle.com/poll/x75vuuc82fbirs9y

(I know this is public sharing the doodle link, hope it is ok for you)

**Comment by lax0248917** [comment]
@mariushilleke Thank you for organizing the training session. If it is posted in slack then there is no need to post the link in a public capacity. Probably safer that we don't just so we don't end up getting spammed with emails 😄

**Review by mariushilleke — APPROVED** [review]
Yes, that should be fine for now.

**Review by lax0248917 — APPROVED** [review]
Looks good to me. Great job resolving the merge conflict. Hope it was a learning experience for all involved.

**Pull request merged**
