### PR TITLE
:rocket: resolve GitHub Issue #14

### PR DESCRIPTION
**Pull request by lax0248917**
The first attempt is to not assign any reviews manually and see if GitHub does the auto-assign on its own.

### CODE REVIEW

**Comment by lax0248917** [comment]
So in this instance the only reviewers were the remaining names in the CODEOWNERS file. This indicates that we will need to manually add the other members. I will attempt to add using our GitHub Team names.

**Comment by lax0248917** [comment]
After clicking on the cog next to Reviewers, I was able to select the "dev-team", this triggered the team auto-assignment set up in our Team Settings, this is currently configured to the max amount of required reviews "3" and choose 3 of the remaining 4 team members in a "Round Robin" fashion. This leaves us one person short from being added to the list.

Solution - manually add last person, manually add all non-codeowners, or accept the new format of creating a pull request and selecting the appropriate team for code review and allowing github to select who will be a part of it.

My thought is that we make a habit of selecting the appropriate team and allow github to select the reviewers as this will be common practice for larger projects and perhaps larger teams. Thoughts?

**Comment by xeho91** [comment]
When I created a Pull Request #17 - it automatically assigned you and @mariushilleke as Reviewers. I was happy with this automation, and I don't mind manually adding other reviewers, if they need to be concerned with specific pulls as well.

**Comment by lax0248917** [comment]
I am good with this approach as well. I like the ability to designate reviewers by selecting the appropriate team. And in future projects as the codebase grows, it will be nice to select individuals when you need specific feedback.

**Comment by lax0248917** [comment]
No need to make this merge. Was for testing purposes only.

**Pull request closed without merging**
