### PR TITLE
:rocket: Change to codeowners file for new code review process

### PR DESCRIPTION
**Pull request by lax0248917**
This change is to help define the code review process. All team members will still be requested to review all pull requests, but for a merge to happen to either the develop or master branches. The PR will need to be APPROVED by the Product Owner and at least one (1) Lead Developer. These individuals are annotated in the CODEOWNERS file.

### CODE REVIEW

**Comment by mariushilleke** [comment]
@lax0248917 it seems that reviewers have to be added manually to pull requests (cf. screenshot), isn't it like everybody who is mentioned in the CODEOWNERS-file will be added automatically as reviewer?

image

**Comment by lax0248917** [comment]
@mariushilleke I did some research looking for a solution for this and perhaps the only way we can add everyone automatically is to create a team within our org and add everyone to the team. That way the team is auto assigned to review pull requests but as of right now the branch is protected by a setting that 2 approvals are required and that those approvals must come from codeowners, so we needed to limit the access in the codeowners file to those we have identified that can approved PRs.

**Comment by lax0248917** [comment]
There might be a workaround!!! What if we set the "Required Reviews" for the branch to 7, then that would force github to add the whole team. right? We leave the approve request to be set to codeowners only, but all can review it.

**Comment by lax0248917** [comment]
Sorry, that workaround is not going to help. That would simply increase the required review approvals.

**Comment by mariushilleke** [comment]
Hmmm, ok. I guess it should be that everybody is added as reviewer, still, then at least manually, til there is another solution, otherwise it will might become a GitHub dev-silo.
But for now then, I approve.

**Pull request merged**
